### ISSUE TITLE
Refactor clientside to be golang wasm

### ISSUE THREAD

**Issue by gedw99** [SamHennessy/hlive#1]
Nice system. 

you could use the golang websocket lib that supports wasm.

then your frontend lib could be golang compiled to wasm.

https://pkg.go.dev/nhooyr.io/websocket

it’s battle tested and used by some significant projects 

This also means you can share the golang types on the backend and frontend for the platform level types.

**Comment by gedw99** [comment]
I do this and with tinygo compilation the wasm goes from 1 mg down to about 20 kb.

The default golang to wasm compiler is really bloaty

**Comment by gedw99** [comment]
Brew install tinygo

**Comment by SamHennessy** [comment]
Thank you for taking the time to suggest using Go in the form of WASM. I think WASM is a fantastic technology and I'm watching it closely. I did consider its use for HLive but after careful consideration using it didn't align with my vision for the project. I want as small a client library as possible that would be simple for people to understand and extend. I was also worried about adding too much risk to the project by adding something like WASM. It's not a technology I understand well and I would want to put a lot more time into it before adding it to this project at such a core place. I want HLive to be something people can trust is written well. 

I do think there is a place for WASM, I would like for it to be an option for developers who want to write client-side code in Go and be deployed with their app. I think based on what we can learn from that we can then see if we want to use it in place of the current JavaScript client library.
