### ISSUE TITLE
offline

### ISSUE THREAD

**Issue by gedw99** [SamHennessy/hlive#2]
Make it run 100% in the browser and 100% offline !!

You can avoid all the network delays by compiling the backend to wasm and run it as a service worker inside the browser.

Here is a golang example doing that: https://github.com/nlepage/go-wasm-http-server .

It compiles to WASM with TinyGo.

Then its all running clientside.

This can run 100% offline also.

SO your coding it all in golang, and deploying it all as wasm.

The Bus between the Service worker and the DOm layer is just replaced with simple message passing.

## Plugins:

You can also add plugins as Web Workers, which are written in golang and compiled to wasm.

Here is example that compiles to WASM and runs as a Web Worker. https://github.com/henrixapp/pdfcomprezzor

## Debugging is easy:

Tinygo WASM is very small. You can fully debug this wasm in Chrome easily, because Tinygo exports the DWARF. Here is how to do with with golang: https://blog.noops.land/debugging-webAssembly-from-go-sources-in-chrome-devtools

## Server && SSR

The websockets can still run inside the Service Worker with no changes except using https://pkg.go.dev/nhooyr.io/websocket, instead of github.com/gorilla/websocket v1.5.0

You still have all the SSR aspects for Google SEO. The exact same code is running on the server and rendering the HTML page and its DOM.

If you want you can run the same WASM on the Server using Wazero too. Works well.  The Host Function is where you send it out over Websockets or SSE.   The same concept applies in the Client as a Service worker, but you're using a different "host Function" to send it to the DOM via Message passing.

So you can have your cake and eat it to.

**Comment by SamHennessy** [comment]
Hi, gedw99. I didn't see you posted here and on Reddit, so I'll post the same response here for others to see. 

Thank you for taking the time to share your thoughts. I agree that wasm is an exciting tech, and I'm watching it closely too. I think your ideas are sound.

I'm currently trying to prove if the way I wanted to work was realistic, which at this point, I think I have. You are correct that using a WebSocket to update the UI introduces an unnecessary lag but how much is too much? Not easy to say, but I feel the lag is not noticeable, and I am happy with the comprise.

My primary use case for HLive is data-rich applications that require a user to be logged in and offer personalisation to that user.

While compiling a Go app down to wasm with TinyGo yields relatively small bundles, they are still in the order of hundreds of KBs. The progress on Go wasm web frameworks seems to have slowed to a crawl, and I think this is also an indication this is currently a dead end. To get good performance for a website, I feel we need to use the smallest amount of bandwidth possible on the initial load.

I also don't see much value in offline support. When needed, a mobile app will be a much stronger choice. Even Google uses a browser plugin to get offline support for Google Docs.

Currently, wasm is single-threaded, but there are plans to overcome that. Wasm doesn't have first-class to the DOM, which hinders performance more, but that may get better in time.

For my purpose and the type of work I do, I'm in love with the idea of using a Websocket to manage the DOM  from Go. I hope this helps explain why I'm not currently pursuing wasm for website work, tho I still think wasm is fantastic for other things.
